import { sql } from 'kysely';
import { createDb, createPool } from '../../src/server/db';
import { scriptDatabase } from '../../src/server/scripts/script-db';
const t = await scriptDatabase();
const db = createDb(createPool(t.url, 1));
const u = await sql<{ email: string; role: string; created_at: Date }>`SELECT email, role, created_at FROM users ORDER BY created_at`.execute(db);
const l = await sql<{ name: string; total: number }>`SELECT name, total FROM lists ORDER BY created_at`.execute(db);
const n = await sql<{ leads: number; tpl: number }>`SELECT (SELECT count(*) FROM leads)::int AS leads, (SELECT count(*) FROM message_templates)::int AS tpl`.execute(db);
console.log(t.url.replace(/:[^:@/]*@/, ':***@'));
console.log(u.rows.map((r) => `${r.role} ${r.email}`).join('\n'));
console.log(l.rows, n.rows);
await db.destroy();
await t.done();
